version: '3'
services:
  nginx:
    ports:
      - "4000:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=tobi
      - MONGO_PASSWORD=samuel
      - SESSION_SECRET=secret
      - REDIS_URL=redis
      - REDIS_PORT=6379
    command: npm run dev
  
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tobi
      - MONGO_INITDB_ROOT_PASSWORD=samuel
